const PDFDocument = require('pdfkit');
const fs = require('fs');

const FONT_CANDIDATES = [
    {
        regular: '/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf',
        bold: '/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf'
    },
    {
        regular: '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
        bold: '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'
    },
    {
        regular: '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf',
        bold: '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'
    },
    {
        regular: '/System/Library/Fonts/Supplemental/Arial Unicode.ttf',
        bold: '/System/Library/Fonts/Supplemental/Arial Bold.ttf'
    },
    {
        regular: '/System/Library/Fonts/Supplemental/Arial.ttf',
        bold: '/System/Library/Fonts/Supplemental/Arial Bold.ttf'
    },
    {
        regular: '/Library/Fonts/Arial Unicode.ttf',
        bold: '/Library/Fonts/Arial Bold.ttf'
    }
];

const resolveFonts = () => {
    const envRegular = process.env.PDF_FONT_REGULAR_PATH;
    const envBold = process.env.PDF_FONT_BOLD_PATH;
    if (envRegular && envBold && fs.existsSync(envRegular) && fs.existsSync(envBold)) {
        return { regular: envRegular, bold: envBold };
    }

    const selected = FONT_CANDIDATES.find(
        (pair) => fs.existsSync(pair.regular) && fs.existsSync(pair.bold)
    );

    if (!selected) {
        console.warn('[pdfService] Unicode font not found, fallback to Helvetica. Cyrillic may render incorrectly.');
        return { regular: 'Helvetica', bold: 'Helvetica-Bold' };
    }

    return selected;
};

const generateEnergyReport = async (data) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const buffers = [];
            const fonts = resolveFonts();

            if (fonts.regular !== 'Helvetica') {
                doc.registerFont('SmartSphere-Regular', fonts.regular);
                doc.registerFont('SmartSphere-Bold', fonts.bold);
            }

            const regularFont = fonts.regular === 'Helvetica' ? 'Helvetica' : 'SmartSphere-Regular';
            const boldFont = fonts.bold === 'Helvetica-Bold' ? 'Helvetica-Bold' : 'SmartSphere-Bold';

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            // Title
            doc.font(boldFont).fontSize(20).text('Energy Report', { align: 'center' });
            doc.moveDown();

            doc.fontSize(12).font(regularFont).text(`Period: ${data.periodDays} days`);
            doc.text(`Date: ${new Date().toLocaleDateString()}`);
            doc.moveDown();

            // Summary
            doc.font(boldFont).text('Summary');
            doc.font(regularFont).text(`Total Consumption: ${data.totalConsumption.toFixed(2)} kWh`);
            doc.text(`Total Cost: ${data.totalCost} KZT`);
            doc.text(`Average Daily: ${data.avgDaily.toFixed(2)} kWh`);
            doc.moveDown();

            // Breakdown (Mock table for now, or simple list)
            doc.font(boldFont).text('Top Consumers');
            data.topConsumers.forEach((device, i) => {
                doc.font(regularFont).text(`${i + 1}. ${device.name}: ${device.kwh.toFixed(2)} kWh`);
            });
            doc.moveDown();

            // Recommendations
            if (data.recommendations.length > 0) {
                doc.font(boldFont).text('Recommendations');
                data.recommendations.forEach(rec => {
                    doc.font(regularFont).text(`- ${rec.title}: Save ~${rec.estimatedKwhSaveMonth} kWh`);
                });
            }

            doc.moveDown();
            doc.font(regularFont).fontSize(10).text('Generated by SmartSphere AI', { align: 'center', color: 'grey' });

            doc.end();
        } catch (e) {
            reject(e);
        }
    });
};

module.exports = { generateEnergyReport };
