const PDFDocument = require('pdfkit');

const generateEnergyReport = async (data) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const buffers = [];

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            // Title
            doc.font('Helvetica-Bold').fontSize(20).text('Energy Report', { align: 'center' });
            doc.moveDown();

            doc.fontSize(12).font('Helvetica').text(`Period: ${data.periodDays} days`);
            doc.text(`Date: ${new Date().toLocaleDateString()}`);
            doc.moveDown();

            // Summary
            doc.font('Helvetica-Bold').text('Summary');
            doc.font('Helvetica').text(`Total Consumption: ${data.totalConsumption.toFixed(2)} kWh`);
            doc.text(`Total Cost: ${data.totalCost} KZT`);
            doc.text(`Average Daily: ${data.avgDaily.toFixed(2)} kWh`);
            doc.moveDown();

            // Breakdown (Mock table for now, or simple list)
            doc.font('Helvetica-Bold').text('Top Consumers');
            data.topConsumers.forEach((device, i) => {
                doc.font('Helvetica').text(`${i + 1}. ${device.name}: ${device.kwh.toFixed(2)} kWh`);
            });
            doc.moveDown();

            // Recommendations
            if (data.recommendations.length > 0) {
                doc.font('Helvetica-Bold').text('Recommendations');
                data.recommendations.forEach(rec => {
                    doc.font('Helvetica').text(`- ${rec.title}: Save ~${rec.estimatedKwhSaveMonth} kWh`);
                });
            }

            doc.moveDown();
            doc.fontSize(10).text('Generated by SmartSphere AI', { align: 'center', color: 'grey' });

            doc.end();
        } catch (e) {
            reject(e);
        }
    });
};

module.exports = { generateEnergyReport };
