const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const FONTS_DIR = path.join(__dirname, '../assets/fonts');

const resolveFonts = () => {
    const robotoRegular = path.join(FONTS_DIR, 'Roboto-Regular.ttf');
    const robotoBold = path.join(FONTS_DIR, 'Roboto-Bold.ttf');

    if (fs.existsSync(robotoRegular) && fs.existsSync(robotoBold)) {
        return { regular: robotoRegular, bold: robotoBold };
    }

    // Fallback candidates
    const CANDIDATES = [
        { regular: '/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf', bold: '/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf' },
        { regular: '/System/Library/Fonts/Supplemental/Arial Unicode.ttf', bold: '/System/Library/Fonts/Supplemental/Arial Bold.ttf' }
    ];

    const selected = CANDIDATES.find(pair => fs.existsSync(pair.regular) && fs.existsSync(pair.bold));

    if (selected) return selected;

    console.warn('[pdfService] Unicode fonts not found. Using Helvetica (Cyrillic may fail).');
    return { regular: 'Helvetica', bold: 'Helvetica-Bold' };
};

const generateEnergyReport = async (data) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const buffers = [];
            const fonts = resolveFonts();

            // Register fonts if not standard
            if (fonts.regular !== 'Helvetica') {
                doc.registerFont('Regular', fonts.regular);
                doc.registerFont('Bold', fonts.bold);
            }

            const fontRegular = fonts.regular === 'Helvetica' ? 'Helvetica' : 'Regular';
            const fontBold = fonts.bold === 'Helvetica-Bold' ? 'Helvetica-Bold' : 'Bold';

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            // Title
            doc.font(fontBold).fontSize(20).text('Energy Report', { align: 'center' });
            doc.moveDown();

            doc.fontSize(12).font(fontRegular).text(`Period: ${data.periodDays} days`, { align: 'center' });
            doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
            doc.moveDown();
            doc.moveDown();

            // Tariff Info
            if (data.tariff) {
                doc.font(fontBold).fontSize(14).text('Tariff Information');
                doc.fontSize(12).font(fontRegular);
                doc.text(`Provider: ${data.tariff.provider}`);
                doc.text(`Region: ${data.tariff.city} (${data.tariff.region})`);
                doc.moveDown();
            }

            // Consumption Summary
            doc.font(fontBold).fontSize(14).text('Consumption Summary');
            doc.fontSize(12).font(fontRegular);
            doc.text(`Total Consumption: ${data.totalConsumption.toFixed(2)} kWh`);
            doc.text(`Estimated Cost: ${data.totalCost} KZT`);
            doc.text(`Average Daily: ${data.avgDaily.toFixed(2)} kWh`);
            doc.moveDown();

            // Top Consumers
            doc.font(fontBold).fontSize(14).text('Top Consumers');
            doc.fontSize(12).font(fontRegular);
            if (data.topConsumers.length > 0) {
                data.topConsumers.forEach((device, i) => {
                    doc.text(`${i + 1}. ${device.name}: ${device.kwh.toFixed(2)} kWh`);
                });
            } else {
                doc.text('No active devices recorded.');
            }
            doc.moveDown();

            // AI Recommendations
            if (data.recommendations && data.recommendations.length > 0) {
                doc.font(fontBold).fontSize(14).text('AI Recommendations');
                doc.fontSize(12).font(fontRegular);
                data.recommendations.forEach(rec => {
                    doc.text(`• ${rec.title}`);
                    doc.fontSize(10).text(`  Reason: ${rec.reason}`);
                    doc.fontSize(10).text(`  Potential Savings: ~${rec.estimatedKwhSaveMonth} kWh/month`);
                    doc.moveDown(0.5);
                    doc.fontSize(12);
                });
            }

            doc.moveDown();
            doc.fontSize(10).fillColor('grey').text('Generated by SmartSphere AI', { align: 'center' });

            doc.end();
        } catch (e) {
            reject(e);
        }
    });
};

module.exports = { generateEnergyReport };
